# Datasource H2 en memoria
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:horarios;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# AWS Bedrock Runtime
quarkus.bedrockruntime.aws.region=us-east-1
quarkus.bedrockruntime.aws.credentials.type=default
quarkus.bedrockruntime.devservices.enabled=false

# Modelo de Bedrock (Claude 3 Haiku - economico y rapido para demos)
bedrock.model-id=anthropic.claude-3-haiku-20240307-v1:0
