quarkus.application.name=student-management-api

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=student
quarkus.datasource.password=student

%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.hibernate-orm.database.generation=update
%dev.quarkus.hibernate-orm.log.sql=true

%prod.quarkus.hibernate-orm.database.generation=update
%prod.quarkus.datasource.username=student
%prod.quarkus.datasource.password=${STUDENT_DB_PASSWORD:change-me}

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

mp.openapi.extensions.smallrye.info.title=Student Management API
mp.openapi.extensions.smallrye.info.version=1.0.0-SNAPSHOT
mp.openapi.extensions.smallrye.info.description=REST API de estudiantes y calificaciones (lab START).

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.http-server.enabled=true

quarkus.otel.service.name=student-management-api
quarkus.otel.traces.sampler=traceidratio
quarkus.otel.traces.sampler.arg=1
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.otel.exporter.otlp.traces.protocol=grpc
%prod.quarkus.otel.sdk.disabled=true
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, spanId=%X{spanId} [%c{2.}] (%t) %s%e%n

%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.otel.sdk.disabled=true
