quarkus.application.name=student-management-api

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=student
quarkus.datasource.password=student

%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.hibernate-orm.database.generation=update
%dev.quarkus.hibernate-orm.log.sql=true

%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.hibernate-orm.database.generation=drop-and-create
