# Dockerfile alternativo usando una imagen base más reciente
FROM fluent/fluentd:latest-debian

# Instalar el plugin de Elasticsearch versión 5.2.2
USER root
RUN gem install fluent-plugin-elasticsearch --version 5.2.2 --no-document
RUN gem list fluent-plugin-elasticsearch
USER fluent
