# Datasource H2 en memoria
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:horarios;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# TODO: Configurar AWS Bedrock Runtime
# quarkus.bedrockruntime.aws.region=
# quarkus.bedrockruntime.aws.credentials.type=
# quarkus.bedrockruntime.devservices.enabled=

# TODO: Configurar el modelo de Bedrock
# bedrock.model-id=
